<MainPage>:
    name: "main"

    canvas.before:
        Rectangle:
            source: "resources/mainbg.jpg"
            size: root.width, root.height

    FloatLayout:
        orientation: "vertical"

        Label:
            id: title
            opacity: 0
            center: 400, -self.height
            text: "SPECTRUM"
            color:(0, 0, 198, 0.56)
            font_size: 60
            size_hint: .0, .0
            pos_hint:{"center_x":0.5, "y":0.7}
            outline_width: 3
            outline_color:(0, 0 ,0)

        FloatLayout:
            orientation: "vertical"

            HoverButtonMainPage:
                size_hint: 0.2, 0.1
                text: "START"
                pos_hint: {"center_x":0.5, "center_y":0.5}
                font_size: 32
                md_bg_color: (0, 130/255, 242/255, 0.8)
                text_color: 1, 1, 1, 1
                line_width: 2
                line_color: 0, 0, 0, 1
                on_release:
                    root.manager.transition.direction = "left"
                    app.root.current = "login"

    AnchorLayout:
        anchor_x: 'right'
        anchor_y: 'bottom'
        pos_hint: {"x":.075}

        Image:
            source: 'resources/kid.gif'
            size_hint: .3, .3

<LoginPage>:
    name: "login"

    canvas.before:
        Rectangle:
            source: "resources/purple_bg3.jpg"
            size: root.width, root.height

    FloatLayout:

        MDIconButton:
            icon: "chevron-left"
            md_bg_color: "snow"
            size_hint: .05, .06
            user_font_size: "40sp"
            pos_hint: {"center_x":.035, "center_y":.95}
            theme_text_color:"Custom"
            text_color: 1, 170/255, 23/255, 1
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "main"

        MDBoxLayout:
            orientation: 'vertical'
            padding: (0, 50, 0, 50)

            MDCard:
                size_hint: 0.6, 0.7
                pos_hint: {"center_x":0.5,"center_y":0.5}
                elevation: 5
                spacing: 25
                orientation: 'vertical'
                line_width:4
                line_color:(0,0,0,0.5)
                padding: (0, 50, 0, 20)
                shadow_radius: 100
                shadow_softness: 60
                radius: [30, 30, 30, 30]

                Label:
                    id: title
                    text: "Your Own PERSONAL Space !"
                    color: "purple"
                    padding: (0, 20, 0, 20)
                    font_size: 40
                    font_style: 'Calibre'
                    size_hint: .1, .1
                    pos_hint: {"center_x":0.5, "y":0.3}
                    outline_width: 3
                    outline_color: (0, 0, 0, 1)

                HoverTextBox:
                    id: uid
                    hint_text: "Username"
                    icon_right: "account"
                    size_hint_x: None
                    width: 200
                    font_size: 20
                    pos_hint: {"center_x": 0.5}

                HoverTextBox:
                    id: pwd
                    hint_text: "Password"
                    icon_right: "lock"
                    size_hint_x: None
                    width: 200
                    font_size: 20
                    pos_hint: {"center_x": 0.5}
                    password: True

                HoverButtonPurpleDesign:
                    text: "LOGIN"
                    font_size: 20
                    pos_hint: {"center_x": 0.5}
                    on_press:
                        root.logIn()
                    line_width: 1.2
                    line_color:"purple"
                    text_color:"purple"
                    md_bg_color:(1,1,1,1)

                HoverButtonPurpleDesign:
                    text: "CLEAR"
                    font_size: 20
                    pos_hint: {"center_x": 0.5}
                    on_press: root.clear()
                    line_width: 1.2
                    line_color:"purple"
                    text_color:"purple"
                    md_bg_color:(1,1,1,1)

                MDLabel:
                    opacity: 0
                    id: error_label
                    text: "Invalid Login"
                    font_size: 14
                    halign: 'center'
                    size_hint_y: None
                    height: self.texture_size[1]
                    pos_hint: {"center_x": 0.5}
                    theme_text_color:'Custom'
                    text_color: 1,0,0,1

                MDLabel:
                    id: signup_label
                    text: "You don't have an account?"
                    font_size: 15
                    halign:'center'
                    pos_hint: {"center_x": 0.5}
                    text_color: 0,0,1,0

                HoverButtonPurpleDesign:
                    id: signup_button
                    text: "SIGN UP"
                    font_size: 25
                    pos_hint: {"center_x": 0.5}
                    line_width: 2
                    theme_text_color: "Custom"
                    line_color:"purple"
                    text_color:"purple"
                    md_bg_color:(1,1,1,1)
                    on_release:
                        root.manager.transition.direction = "left"
                        app.root.current = "signup"

                MDAnchorLayout:
                    anchor_x: 'right'
                    anchor_y: 'bottom'
                    size_hint: 20.1, 20.1
                    pos_hint: {"center_x": 0.5}

                    Image:
                        id: circle
                        opacity: 0
                        source: 'resources/circle.gif'


<SignupPage>:
    name:'signup'

    canvas.before:
        Rectangle:
            source: 'resources/purple_bg2.png'
            size: root.width, root.height

    MDIconButton:
        icon: "chevron-left"
        md_bg_color: "snow"
        size_hint: .05, .06
        user_font_size: "40sp"
        pos_hint: {"center_x":.035, "center_y":.95}
        theme_text_color:"Custom"
        text_color: 1, 170/255, 23/255, 1
        on_release:
            root.manager.transition.direction = "right"
            root.manager.current = "main"

    BoxLayout:
        orientation: 'vertical'
        padding: (0, 50, 0, 50)

        MDCard:
            size_hint: 0.6, 0.7
            pos_hint: {"center_x":0.5,"center_y":0.5}
            elevation: 5
            spacing: 25
            padding: (0, 50, 0, 100)
            orientation: 'vertical'
            line_width:4
            line_color:(0,0,0,0.5)
            shadow_radius: 100
            shadow_softness: 60
            radius: [30, 30, 30, 30]

            Label:
                id: title
                text: "Create an account"
                color:"purple"
                font_size:50
                size_hint:.1,.1
                pos_hint:{"center_x":0.5, "y":0.3}
                outline_width: 3
                outline_color:(0,0,0,1)

            HoverTextBox:
                id: uid
                hint_text: "Username"
                icon_right: "account"
                size_hint_x: None
                width: 200
                font_size: 20
                pos_hint: {"center_x": 0.5}

            HoverTextBox:
                id: pwd
                hint_text: "Password"
                icon_right: "lock"
                size_hint_x: None
                width: 200
                font_size: 20
                pos_hint: {"center_x": 0.5}
                password: True

            HoverTextBox:
                id: repwd
                hint_text: "Repeat Password"
                icon_right: "lock"
                size_hint_x: None
                width: 200
                font_size: 20
                pos_hint: {"center_x": 0.5}
                password: True

            MDLabel:
                opacity: 0
                id: error_label
                text: "Account already exists!"
                font_size: 14
                halign: 'center'
                size_hint_y: None
                height: self.texture_size[1]
                pos_hint: {"center_x": 0.5}
                theme_text_color:'Custom'
                text_color: 1,0,0,1

            HoverButtonPurpleDesign:
                id: signup_button
                text: "SIGN UP"
                font_size: 25
                pos_hint: {"center_x": 0.5}
                line_width: 2
                theme_text_color: "Custom"
                line_color: "black"
                text_color: "black"
                md_bg_color: (1, 1, 1, 1)
                on_press: root.create_account()

            HoverButtonPurpleDesign:
                id: back_button
                text: "GO BACK"
                font_size: 25
                pos_hint: {"center_x": 0.5}
                line_width: 2
                theme_text_color: "Custom"
                line_color:"purple"
                text_color:"purple"
                md_bg_color:(1,1,1,1)

                on_release:
                    root.manager.transition.direction = "right"
                    app.root.current = "login"

<SuccessfulSignupPage>:
    name: 'success'

    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'resources/purple_bg4.png'

    MDCard:
        md_bg_color: "wheat"
        size_hint:.8,.5
        pos_hint:{"center_x":0.5, "center_y":0.5}
        elevation: 5
        padding: 25
        spacing: 25
        orientation: 'vertical'
        line_width:4
        line_color:(0,0,0,0.5)
        shadow_radius: 100
        shadow_softness: 60
        radius: [30, 30, 30, 30]

        Label:
            id: title
            text: "Successfully created!"
            color: "purple"
            font_size: 50
            size_hint: .1,.1
            pos_hint: {"center_x":0.5, "y":0.3}
            outline_width: 3
            outline_color: (0, 0, 0, 1)

        HoverButtonPurpleDesign:
            id: signup_button
            text: "LOGIN"
            font_size: 25
            pos_hint: {"center_x": 0.5}
            line_width: 2
            theme_text_color: "Custom"
            line_color:"purple"
            text_color:"purple"
            md_bg_color: (1, 1, 1, 1)
            on_release:
                root.manager.transition.direction = "right"
                app.root.current = "login"

<ChooseTypeAccountPage>:
    name: "choose_type_account"

    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'resources/orange_bg2.jpg'

    BoxLayout:
        orientation: 'horizontal'
        spacing: 40
        padding: (40, 0, 40, 0)

        HoverCardChooseProfile:
            orientation: 'vertical'
            size_hint: 0.3, 0.5
            pos_hint: {"center_x":0.5, "center_y":0.5}
            font_size: 32
            md_bg_color: (255, 255, 255, 1)
            text_color: 1, 1, 1, 1
            line_width: 2
            line_color: 0, 0, 0, 1
            elevation: 3
            spacing: 25
            padding: (0, 50, 0, 50)
            shadow_radius: 50
            shadow_softness: 60
            radius: [30, 30, 30, 30]

            on_release:
                root.manager.transition.direction = "left"
                app.root.current = "checks_page"

            Image:
                pos_hint: {"center_x":0.5, "center_y":0.5}
                source: 'resources/adult_with_kid.png'
                size_hint: .5, .5

            Label:
                text: "PARENTAL"
                color: (0, 130/255, 242/255, 0.8)
                padding: (0, 20, 0, 20)
                font_size: 40
                font_style: 'Calibre'
                size_hint: .1, .1
                pos_hint: {"center_x":0.5, "y":0.3}
                outline_width: 3
                outline_color: (0, 0, 0, 1)

        HoverCardChooseProfile:
            orientation: 'vertical'
            size_hint: 0.3, 0.5
            pos_hint: {"center_x":0.5, "center_y":0.5}
            font_size: 32
            md_bg_color: (255, 255, 255, 1)
            text_color: 1, 1, 1, 1
            line_width: 2
            line_color: 0, 0, 0, 1
            elevation: 3
            spacing: 25
            padding: (0, 50, 0, 50)
            shadow_radius: 50
            shadow_softness: 60
            radius: [30, 30, 30, 30]

            on_release:
                root.manager.transition.direction = "left"
                app.root.current = "checks_page"

            Image:
                pos_hint: {"center_x":0.5, "center_y":0.5}
                source: 'resources/adult.png'
                size_hint: .5, .5

            Label:
                text: "PERSONAL"
                color: (0, 130/255, 242/255, 0.8)
                padding: (0, 20, 0, 20)
                font_size: 40
                font_style: 'Calibre'
                size_hint: .1, .1
                pos_hint: {"center_x":0.5, "y":0.3}
                outline_width: 3
                outline_color: (0, 0, 0, 1)

<CheckFunctionalitiesPage>
    name: "checks_page"

    MDIconButton:
        icon: "chevron-left"
        md_bg_color: "snow"
        size_hint: .05, .06
        user_font_size: "40sp"
        pos_hint: {"center_x":.035, "center_y":.95}
        theme_text_color:"Custom"
        text_color: 1, 170/255, 23/255, 1
        on_release:
            root.manager.transition.direction = "right"
            root.manager.current = "choose_type_account"

    GridLayout:
        cols:1
        spacing: 25
        padding: 25

        Label:
            id: title
            text: "Choose Your Tools !"
            color: "white"
            font_size: 50
            size_hint: .1,.1
            pos_hint: {"center_x":0.5, "y":0.3}
            outline_width: 3
            outline_color: (0, 0, 0, 1)

        ScrollView:
            bar_width: 5
            MDList:
                id: scroll
                md_bg_color: "wheat"

                TwoLineAvatarIconListItem:
                    id: p1
                    text: "Daily Diary"
                    secondary_text: "Write how your day went in you own personal space! (COMING SOON!)"
                    icon: "pencil"

                    IconLeftWidget:
                        id: i1
                        icon: "pencil"

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p110
                            on_active:
                                root.check_click(self, self.active, root.ids.p1.text)
                                #app.save_checked(*args,root.ids.mm1.text,root.ids.mm1.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p2
                    text: "Emotions Diary"
                    secondary_text: "Track your mood every single day!"
                    icon: "emoticon-happy"

                    IconLeftWidget:
                        id: i2
                        icon: "emoticon-happy" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p210
                            on_active:
                                root.check_click(self, self.active, root.ids.p2.text)
                                #app.save_checked(*args,root.ids.mm2.text,root.ids.mm2.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p3
                    text: "Acknowledgements Diary"
                    secondary_text: "Put down all your past accomplishments, present struggles and future dreams! (COMING SOON!)"
                    icon: "star-box-outline"

                    IconLeftWidget:
                        id: i3
                        icon: "star-box-outline" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p310
                            on_active:
                                root.check_click(self, self.active, root.ids.p3.text)
                                #app.save_checked(*args,root.ids.mm6.text,root.ids.mm6.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p4
                    text: "To-Do List"
                    secondary_text: "List all your personal chores and do them one by one!"
                    icon: "check-decagram"

                    IconLeftWidget:
                        id: i4
                        icon: "check-decagram" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p410
                            on_active:
                                root.check_click(self, self.active, root.ids.p4.text)
                                #app.save_checked(*args,root.ids.mm3.text,root.ids.mm3.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p5
                    text: "Scheduler"
                    secondary_text: "Keep track of your routine and daily tasks! (COMING SOON!)"
                    icon: "view-list"

                    IconLeftWidget:
                        id: i5
                        icon: "view-list" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p510
                            on_active:
                                root.check_click(self, self.active, root.ids.p5.text)
                                #app.save_checked(*args,root.ids.mm4.text,root.ids.mm4.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p6
                    text: "Text To Speech"
                    secondary_text: "Another way to communicate freely!"
                    icon: "microphone"

                    IconLeftWidget:
                        id: i6
                        icon: "microphone" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p610
                            on_active:
                                root.check_click(self, self.active, root.ids.p6.text)
                                #app.save_checked(*args,root.ids.mm5.text,root.ids.mm5.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p7
                    text: "Shopping List"
                    secondary_text: "Don't forget your groceries!"
                    icon: "shopping"

                    IconLeftWidget:
                        id: i7
                        icon: "shopping" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p710
                            on_active:
                                root.check_click(self, self.active, root.ids.p7.text)
                                #app.save_checked(*args,root.ids.mm6.text,root.ids.mm6.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p8
                    text: "Book Manager"
                    secondary_text: "Have all your book titles in one place! (COMING SOON!)"
                    icon: "book"

                    IconLeftWidget:
                        id: i8
                        icon: "book" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p810
                            on_active:
                                root.check_click(self, self.active, root.ids.p8.text)
                                #app.save_checked(*args,root.ids.mm6.text,root.ids.mm6.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p9
                    text: "Hobby Roulette"
                    secondary_text: "Have all your movie and series titles in one place!"
                    icon: "movie"

                    IconLeftWidget:
                        id: i9
                        icon: "movie" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p910
                            on_active:
                                #root.is_clicked(self, self.active, root.ids.p9.text)
                                root.check_click(self, self.active, root.ids.p9.text)
                                #app.save_checked(*args,root.ids.mm6.text,root.ids.mm6.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p10
                    text: "Find Your Home!"
                    secondary_text: "Don't ever forget the path to your home!"
                    icon: "map"

                    IconLeftWidget:
                        id: i10
                        icon: "map" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p1010
                            on_active:
                                #root.is_clicked(self, self.active, root.ids.p10.text)
                                root.check_click(self, self.active, root.ids.p10.text)
                                #app.save_checked(*args,root.ids.mm6.text,root.ids.mm6.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p11
                    text: "Speech To Text"
                    secondary_text: "Convert your voice to written text! (COMING SOON!)"
                    icon: "map"

                    IconLeftWidget:
                        id: i11
                        icon: "volume-high" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p1110
                            on_active:
                                #root.is_clicked(self, self.active, root.ids.p11.text)
                                root.check_click(self, self.active, root.ids.p11.text)
                                #app.save_checked(*args,root.ids.mm6.text,root.ids.mm6.secondary_text,root.ids.i1.icon,root)

                TwoLineAvatarIconListItem:
                    id: p12
                    text: "Chat Room"
                    secondary_text: "Find friends to talk with! (COMING SOON!)"
                    icon: "map"

                    IconLeftWidget:
                        id: i12
                        icon: "chat" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p1210
                            on_active:
                                #root.is_clicked(self, self.active, root.ids.p12.text)
                                root.check_click(self, self.active, root.ids.p12.text)
                                #app.save_checked(*args,root.ids.mm6.text,root.ids.mm6.secondary_text,root.ids.i1.icon,root)


                TwoLineAvatarIconListItem:
                    id: p13
                    text: "Anti-Stress Doodles"
                    secondary_text: "A magic pen will doodle for you and create figures, while you relax!(COMING SOON!)"
                    icon: "map"

                    IconLeftWidget:
                        id: i13
                        icon: "brush-variant" #root.icon

                    IconRightWidget:
                        icon: "resources/transparent.png"
                        MDCheckbox:
                            id: p1310
                            on_active:
                                #root.is_clicked(self, self.active, root.ids.p13.text)
                                root.check_click(self, self.active, root.ids.p13.text)
                                #app.save_checked(*args,root.ids.mm6.text,root.ids.mm6.secondary_text,root.ids.i1.icon,root)


        HoverButtonSaveChecks:
            id: cm
            text: "Save"
            font_size: 20
            size_hint: .10, .10
            on_release: root.save_checked()

<CustomDialog>:
    title: "Please follow the guideline below:"
    text: "For a strong password you should include the following:\n - one capital letter\n - two small letters\n - one number\n - one special symbol (!, @, #, $, %, ^, &, *)\n"
    elevation: 6
    shadow_radius: 18
    shadow_softness: 24
    shadow_offset: 12, 12
    radius: [20, 20, 20, 20]

    BoxLayout:
        orientation: 'vertical'
        padding: (0, 0, 0, 20)
        MDFlatButton:
            size_hint_y: None
            elevation: 5
            pos_hint:{"center_x": 0.5}
            text: "OK"
            theme_text_color: "Custom"
            text_color: self.theme_cls.primary_color
            on_release: root.dismiss()


<ProfilePage>:
    name: 'profile_page'

    AnchorLayout:
        anchor_y:'top'

        MDGridLayout:
            cols:1
            #padding:20
            #spacing:20

            MDTopAppBar:
                id: top
                title: "SPECTRUM"
                #md_bg_color: app.theme_cls.accent_color
                left_action_items: [["menu", lambda x: root.drop_func(x)]]
                right_action_items: [["theme-light-dark", lambda x: root.change_theme(app)], ["brush-variant", lambda x: root.change_but_color(app, root)], ["palette", lambda x: root.show_theme_picker(app)]]

            ScrollView:
                size_hint_x: 1
                size_hint_y: None
                size: 800, 600

                GridLayout:
                    cols:3
                    row_default_height: 250
                    row_force_default: True
                    height: 900
                    padding:[dp(15),dp(15),dp(15),dp(40)]
                    spacing:dp(25)
                    size_hint_y: None

                    ElementCard:
                        image: "resources/to-do.png"
                        id: e4
                        text:"To-Do List"
                        on_release:
                            app.root.current = "todolist"

                    ElementCard:
                        image: "resources/hobby.png"
                        id: e9
                        text:"Hobby Roulette"
                        on_release:
                            app.root.current = "hobbyroulette"

                    ElementCard:
                        image: "resources/cart.png"
                        id: e7
                        text:"Shopping List"
                        on_release:
                            app.root.current = "shopping"

                    ElementCard:
                        image: "resources/map.png"
                        id: e10
                        text:"Find Your Home!"
                        on_release:
                            app.root.current = "findyourhome"

                    ElementCard:
                        image: "resources/emotion.png"
                        id: e2
                        text:"Emotions Diary"
                        on_release:
                            app.root.current = "emotion"

                    ElementCard:
                        image: "resources/speech.png"
                        id: e6
                        text:"Text To Speech"
                        on_release:
                            app.root.current = "texttospeech"

                    ElementCard:
                        image: "resources/diary.png"
                        id: e1
                        text:"Daily Diary"
                        on_release:
                            app.root.current = "dailydiary"

                    ElementCard:
                        image: "resources/doodle.png"
                        id: e13
                        text:"Anti-Stress Doodles"
                        on_release:
                            app.root.current = "doodles"


            MDBottomAppBar
                MDTopAppBar:
                    id: bot
                    title: "ORGANISE YOUR SPACE!"
                    icon: "plus"
                    type: "bottom"
                    #on_action_button: root.create_page()
                    on_action_button:
                        root.manager.transition.direction = "right"
                        root.create_page()
                    right_action_items: [["emoticon-happy", lambda x: root.show_confirmation_dialog()]]

<ElementCard@MDCard>:
   #size: "280dp", "180dp"
    #pos_hint: {"center_x": .5, "center_y": .5}
    md_bg_color: "wheat"
    padding:dp(15)
    spacing:dp(15)
    radius:dp(25)
    ripple_behavior: True
    elevation: 3
    image:''
    text:""

    orientation:'vertical'
    Image:
        size_hint_y:.90
        source:root.image
    MDLabel:
        halign: "center"
        size_hint_y:.10
        text:root.text

<ListItem@OneLineAvatarIconListItem>:
    IconLeftWidget:
        id: i1
        icon:"shopping-outline"
    ItemCheckBox:

<TodoCard>:
    done: root.out_done

    elevation: 2
    md_bg_color: 1,1,1,1
    radius: [8]

    MDFloatLayout:
        id: bar
        size_hint: .01, .9
        pos_hint: {"center_x": .02, "center_y":.5}
        md_bg_color: 1, 170/255, 23/255, 1

    MDLabel:
        id: title
        text: root.title
        markup: True
        font_name: "resources/Poppins-SemiBold.ttf"
        font_size: "20sp"
        size_hint_x: .8
        pos_hint:{"center_x": .46, "center_y": .8}

    Image:
        id: image
        #orientation: "vertical"
        #size_hint: 1, .75
        pos_hint: {"center_x": .75, "center_y": .8}
        source: root.image

    MDCheckbox:
        id: check
        size_hint: None, None
        size:"48dp", "48dp"
        unselected_color: 1,170/255, 23/255,1
        selected_color: 0,179/255, 0,1
        pos_hint:{"center_x": .95, "center_y": .8}
        on_active:
            #root.manager.ids("todolist").on_complete(*args, description, bar)
            root.effects(*args, root.id, title, description, bar)
    MDLabel:
        id: description
        text: root.description
        font_name: "resources/Poppins-Semibold.ttf"
        markup: True
        size_hint_x: .9
        line_height: .8
        pos_hint: {"center_x": .51, "center_y": .4}

    MDLabel:
        id: due_date
        text: root.due_date
        markup: True
        size_hint: .4, .4
        color: "grey"
        font_name: "resources/Poppins-Regular.ttf"
        pos_hint: {"center_x": .8, "center_y": .2}

    MDIconButton:
        id: deleter
        icon: "trash-can"
        user_font_size: "40sp"
        pos_hint: {"center_x":.95, "center_y":.2}
        theme_text_color:"Custom"
        text_color: 1, 170/255, 23/255, 1
        on_release:
            #self.parent.remove_widget(self)
            root.remove_effects(*args, root.id, title, description, bar)

<AddListBox>:
    title: title
    description: description
    priority: image
    due_date: due_date

    name: "add_todo_box"
    MDFloatLayout:
        #md_bg_color: 1,1,1,1
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'white.png'
        MDIconButton:
            icon: "chevron-left"
            user_font_size: "40sp"
            pos_hint: {"center_y":.95}
            theme_text_color:"Custom"
            text_color: 1, 170/255, 23/255, 1
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "todolist"
        MDLabel:
            text: "Add Task"
            pos_hint: {"center_x": .8, "center_y":.88}
            font_name: "resources/Poppins-SemiBold.ttf"
            font_size:"35sp"
        MDFloatLayout:
            size_hint: .85, .08
            pos_hint: {"center_x": .5, "center_y":.78}
            canvas:
                Color:
                    rgba:(1,1,1,1)
                RoundedRectangle:
                    size:self.size
                    pos:self.pos
                    radius:[25]
                Line:
                    width: 2
                    rectangle: self.x, self.y, self.width, self.height
            TextInput:
                id: title
                hint_text:"Title"
                hint_text_color: (0,0,0,0.5)
                size_hint:1,None
                pos_hint: {"center_x": .5, "center_y":.5}
                height: self.minimum_height
                multiline: False
                cursor_color: 1, 170/255, 23/255, 1
                cursor_width: "2sp"
                foreground_color: 1, 170/255, 23/255, 1
                background_color:0,0,0,0
                padding:15
                font_name: "resources/Poppins-Regular.ttf"
                font_size:"18sp"
        MDFloatLayout:
            size_hint: .85, .28
            pos_hint: {"center_x": .5, "center_y":.57}
            canvas:
                Color:
                    rgba:(1,1,1,1)
                RoundedRectangle:
                    size:self.size
                    pos:self.pos
                    radius:[25]
                Line:
                    width: 2
                    rectangle: self.x, self.y, self.width, self.height
            TextInput:
                id: description
                hint_text:"Description"
                hint_text_color: (0,0,0,0.5)
                size_hint:1,None
                pos_hint: {"center_x": .5, "center_y":.5}
                height: 180
                cursor_color: 1, 170/255, 23/255, 1
                cursor_width: "2sp"
                foreground_color: 1, 170/255, 23/255, 1
                background_color:0,0,0,0
                padding:15
                font_name: "resources/Poppins-Regular.ttf"
                font_size:"18sp"

        MDFloatLayout:
            size_hint: .85, .08
            pos_hint: {"center_x": .5, "center_y":.36}
            canvas:
                Color:
                    rgba:(1,1,1,1)
                RoundedRectangle:
                    size:self.size
                    pos:self.pos
                    radius:[25]
                Line:
                    width: 2
                    rectangle: self.x, self.y, self.width, self.height
            TextInput:
                id: image
                hint_text:"Priority (1 to 5)"
                hint_text_color: (0,0,0,0.5)
                size_hint:1,None
                pos_hint: {"center_x": .5, "center_y":.5}
                height: self.minimum_height
                multiline: False
                cursor_color: 1, 170/255, 23/255, 1
                cursor_width: "2sp"
                foreground_color: 1, 170/255, 23/255, 1
                background_color:0,0,0,0
                padding:15
                font_name: "resources/Poppins-Regular.ttf"
                font_size:"18sp"

        MDBoxLayout:
            orientation: 'horizontal'
            padding: (55, 30, 55, 15)
            spacing: 10

            MDIconButton:
                icon: 'calendar'
                size_hint: .02, .08
                pos_hint: {"center_x": .35, "center_y":.25}
                md_bg_color: 1, 1, 1, 1
                on_release:
                    root.show_date_picker()

            MDLabel:
                id: due_date
                text: "No Due"
                size_hint: .1, .05
                font_size: 20
                halign: 'center'
                font_name: "resources/Poppins-Regular.ttf"
                pos_hint: {"center_x": .8, "center_y":.25}

                canvas.before:
                    Color:
                        rgba: (1,1,1,1)
                    RoundedRectangle:
                        size:self.size
                        pos:self.pos
                        radius:[25]

        Button:
            text: "ADD TASK"
            size_hint: .45, .08
            pos_hint: {"center_x": .5, "center_y":.15}
            font_name: "resources/Poppins-SemiBold.ttf"
            background_color:0,0,0,0
            font_size:"18sp"
            color:1,1,1,1
            on_release:
                root.manager.get_screen('todolist').add_todo_box(title.text, description.text, image.text, due_date.text, 0)
                #root.manager.current = 'todolist'
            canvas.before:
                Color:
                    rgb:(1, 170/255, 23/255, 1)
                RoundedRectangle:
                    size:self.size
                    pos:self.pos
                    radius:[25]


<TODOListBox>:
    name: "todolist"
    id: todolist
    todo_list: todo_list
    MDFloatLayout:
        #md_bg_color: 1,1,1,1
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'white.webp'
        MDIconButton:
            icon: "chevron-left"
            user_font_size: "40sp"
            pos_hint: {"center_y":.95}
            theme_text_color:"Custom"
            text_color: 1, 170/255, 23/255, 1
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "profile_page"
        MDLabel:
            text: "All Tasks"
            pos_hint: {"center_x": .75, "center_y": .95}
            font_name: "resources/Poppins-Semibold.ttf"
            font_size: "35sp"
        MDLabel:
            id: date
            text: ""
            pos_hint:{"center_x": .72, "center_y":.89}
            font_name: "resources/Poppins-Regular.ttf"
            font_size: "18sp"
        MDIconButton:
            icon: "plus"
            pos_hint: {"center_x": .89, "center_y": .925}
            user_font_data: "30sp"
            md_bg_color: 1,170/255, 23/255,1
            theme_text_color:"Custom"
            text_color:1,1,1,1
            on_release:
                #root.add_todo()
                root.manager.current = "add_todo_box"
                root.manager.transition.direction = "left"
        ScrollView:
            do_scroll_y:True
            do_scroll_x:False
            size_hint_y: .85
            pos_hint: {"center_x": .5, "y":0}
            bar_width:0
            GridLayout:
                id: todo_list
                cols: 1
                height: self.minimum_height
                row_default_height: 80
                size_hint_y: None
                padding: 15,10
                spacing: 15,10

<VerticalDatePicker>:
    orientation: 'vertical'

<TextToSpeech>
    name:"texttospeech"
    id:texttospeech
    MDFloatLayout:
        MDIconButton:
            icon: "chevron-left"
            user_font_size: "40sp"
            pos_hint: {"center_y":.95}
            theme_text_color:"Custom"
            text_color: 1, 170/255, 23/255, 1
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "profile_page"
        MDLabel:
            text: "Text To Speech"
            font_name: "resources/Poppins-Semibold.ttf"
            pos_hint:{"center_y": .80}
            bold: True
            font_style: "H3"
            halign: "center"
        MDTextField:
            id:text
            hint_text: "Enter Text"
            size_hint_x:.8
            pos_hint:{"center_x":.5, "center_y": .4}
        HoverButtonOriginal:
            elevation: 3
            text: "Speak!"
            size_hint: .45, .08
            pos_hint:{"center_x":.5, "center_y": .25}
            on_release: root.speak()
            font_name: "resources/Poppins-SemiBold.ttf"
            background_color:0,0,0,0
            font_size:"18sp"
            color:1,1,1,1
            ripple_behavior: True
            canvas.before:
                Color:
                    rgb:(1, 170/255, 23/255, 1)
                RoundedRectangle:
                    size:self.size
                    pos:self.pos
                    radius:[25]
        MDFloatLayout:
            orientation: 'horizontal'
            MDIconButton:
                pos_hint: {"center_x":.35, "center_y": .1}
                icon: "resources/man.png"
                icon_size: "40sp"
                on_release: root.change_voice_male()
            MDIconButton:
                pos_hint: {"center_x":.65, "center_y": .1}
                icon: "resources/woman.png"
                icon_size: "40sp"
                on_release: root.change_voice_female()

<HobbyCard>:
    elevation: 2
    md_bg_color:"#ffb900"
    radius: [8]
    size_hint_x: .1
    #pos_hint: {"center_y":.8}
    MDLabel:
        id: title
        text: root.title
        markup: True
        font_name: "resources/Poppins-SemiBold.ttf"
        font_size: "20sp"
        size_hint_x: .8
        pos_hint:{"center_x": .46, "center_y": .6}


<HobbyRoulette>:
    name: "hobbyroulette"
    id: hobbyroulette
    hobbies_list: hobbies_list

    MDFloatLayout:
        MDIconButton:
            icon: "chevron-left"
            user_font_size: "40sp"
            pos_hint: {"center_y":.95}
            theme_text_color:"Custom"
            text_color: 1, 170/255, 23/255, 1
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "profile_page"
        MDLabel:
            text: "Pick Your Hobby!"
            color: "brown"
            pos_hint: {"center_x": .75, "center_y": .95}
            font_name: "resources/Poppins-Semibold.ttf"
            font_size: "35sp"

        ScrollView:
            do_scroll_y:True
            do_scroll_x:False
            size_hint_y: .3
            pos_hint: {"center_x": .5, "center_y":.75}
            bar_width:0
            GridLayout:
                id: hobbies_list
                cols: 1
                height: self.minimum_height
                row_default_height: 50
                size_hint_y: None
                padding: 15,10
                spacing: 15,10

        MDFloatLayout:
            size_hint: .50, .08
            pos_hint: {"center_x": .5, "center_y":.30}
            canvas:
                Color:
                    rgba:(0,0,0,0.5)
                RoundedRectangle:
                    size:self.size
                    pos:self.pos
                    radius:[25]
            TextInput:
                id:randomize
                disabled:True
                hint_text:"Randomize Hobby!"
                hint_text_color: (1,1,1,1)
                size_hint:1,None
                pos_hint: {"center_x": .5, "center_y":.5}
                height: self.minimum_height
                multiline: False
                cursor_color: 1, 170/255, 23/255, 1
                cursor_width: "2sp"
                foreground_color: 1, 170/255, 23/255, 1
                background_color:0,0,0,0
                padding:15
                font_name: "resources/Poppins-Regular.ttf"
                font_size:"18sp"

        MDFillRoundFlatButton:
            text: "Randomize"
            line_color:"black"
            text_color:"white"
            md_bg_color:"#ffb900"
            font_size: 20
            line_width: 1.2
            pos_hint: {"center_x": .5, "center_y": .40}
            on_press: root.randomize()
        Label:
            text:" "
            font_size: 25
        BoxLayout:
            padding: 20
            spacing: 20
            pos_hint: {"center_x": .5, "center_y": .3}
            MDTextField:
                size_hint_x: .5
                pos_hint: {"center_x": .5, "center_y": .30}
                id: new_item
                hint_text: "Enter New Hobby!"
                helper_text_mode: "on_focus"

            MDFillRoundFlatButton:
                text: "Add Hobby"
                line_color:"black"
                text_color:"white"
                md_bg_color:"brown"
                font_size: 20
                line_width: 1.2
                pos_hint: {"center_x": .5, "center_y": .30}
                on_press: root.add_entry(new_item.text, False)

<AntistressDoodlesPage>:
    name: "doodles"
    id: doodles
    doodles: doodles
    md_bg_color: 163/255, 255/255, 172/255, 0.8

    MDFloatLayout:
        MDIconButton:
            icon: "chevron-left"
            user_font_size: "40sp"
            pos_hint: {"center_y":.95}
            theme_text_color:"Custom"
            text_color: 1, 170/255, 23/255, 1
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "profile_page"


    MDBoxLayout:
        pos_hint: {'center_x': .5}
        orientation: "vertical"
        adaptive_width: True
        spacing:dp(30)

        MDLabel:
            text: "Pick A Doodle!"
            color: 0, 62/255, 6/255, 0.8
            pos_hint: {"center_x": 0.75, "center_y": .95}
            font_name: "resources/Poppins-Semibold.ttf"
            font_size: "35sp"

        Image:
            source: 'resources/turtle.png'
            size_hint: .7, .7
            pos_hint: {"center_x":0.5, "center_y":0.5}

        GridLayout:
            cols: 3
            size_hint: None, None
            size: self.minimum_size
            padding:[dp(15),dp(15),dp(15),dp(150)]
            spacing:dp(25)

            MDFillRoundFlatButton:
                text: "Benzene"
                line_color:"black"
                text_color:"white"
                md_bg_color:"#ffb900"
                font_size: 30
                line_width: 1.2
                on_press: root.draw_benzene_screen()

            MDFillRoundFlatButton:
                text: "Tree"
                line_color:"black"
                text_color:"white"
                md_bg_color:"#ffb900"
                font_size: 30
                line_width: 1.2
                on_press: root.draw_tree_screen()

            MDFillRoundFlatButton:
                text: "Colorful Tree"
                line_color:"black"
                text_color:"white"
                md_bg_color:"#ffb900"
                font_size: 30
                line_width: 1.2
                on_press: root.draw_colorful_tree_screen()

            MDFillRoundFlatButton:
                text: "Spiral"
                line_color:"black"
                text_color:"white"
                md_bg_color:"#ffb900"
                font_size: 30
                line_width: 1.2
                on_press: root.draw_spiral_screen()

            MDFillRoundFlatButton:
                text: "Helix"
                line_color:"black"
                text_color:"white"
                md_bg_color:"#ffb900"
                font_size: 30
                line_width: 1.2
                on_press: root.draw_helix_screen()

            MDFillRoundFlatButton:
                text: "Stars"
                line_color:"black"
                text_color:"white"
                md_bg_color:"#ffb900"
                font_size: 30
                line_width: 1.2
                on_press: root.draw_stars_screen()


<ItemEmotion>
    ImageLeftWidget:
        source: root.source

<ContentEmotion>
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "120dp"

    BoxLayout:
        orientation: "horizontal"
    MDTextField:
        id: field
        hint_text: "Thoughts Of Today:"

<EmotionsCard>:
    elevation: 2
    md_bg_color: "wheat"
    radius: [8]
    #size_hint_y: .1
    #pos_hint: {"center_y":.8}
    MDLabel:
        id: title
        text: root.title
        markup: True
        font_name: "resources/Poppins-SemiBold.ttf"
        font_size: "20sp"
        size_hint_x: .8
        pos_hint:{"center_x": .46, "center_y": .6}
    MDLabel:
        id:date
        text: root.date
        font_name: "resources/Poppins-SemiBold.ttf"
        multiline: True
        size_hint_x: .9
        line_height: .8
        pos_hint: {"center_x": .51, "center_y": .35}

    MDLabel:
        id:description
        text: root.description
        font_name: "resources/Poppins-SemiBold.ttf"
        multiline: True
        markup: True
        size_hint_x: .9
        line_height: .8
        pos_hint: {"center_x": .51, "center_y": .05}


<Emotion>:
    name: "emotion"
    emotions_list: emotions_list
    MDFloatLayout:
        #md_bg_color: 1,1,1,1
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'white.webp'
        MDIconButton:
            icon: "chevron-left"
            user_font_size: "40sp"
            pos_hint: {"center_y":.95}
            theme_text_color:"Custom"
            text_color: 1, 170/255, 23/255, 1
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "profile_page"
        MDLabel:
            text: "All Entries"
            pos_hint: {"center_x": .80, "center_y": .95}
            font_name: "resources/Poppins-Semibold.ttf"
            font_size: "35sp"
        ScrollView:
            do_scroll_y:True
            do_scroll_x:False
            size_hint_y: .85
            pos_hint: {"center_x": .5, "y":0}
            bar_width:0
            GridLayout:
                id: emotions_list
                cols: 1
                height: self.minimum_height
                row_default_height: 80
                size_hint_y: None
                padding: 15,10
                spacing: 15,10